spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://${CONFIG_SERVER_URL:localhost:8071}/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
  data:
    redis:
      connect-timeout: 1000
      host: localhost
      port: 6379
      timeout: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: api-gateway
    description: API Gateway Microservice
    version: 1.0.0

logging:
  level:
    com:
      bhavesh16281:
        api_gateway: DEBUG

# resilience4j.circuitbreaker:
#   configs:
#     default:
#       slidingWindowSize: 10
#       permittedNumberOfCallsInHalfOpenState: 2
#       waitDurationInOpenState: 10000
#       failureRateThreshold: 50
  
